(function () {
  document.write('<header>');
  document.write('  <div class="logo">');
  document.write('    <a href="index.html" aria-label="返回主页">');
  document.write('      <img src="./images/logo.png" alt="欢乐豆工作室">');
  document.write('    </a>');
  document.write('  </div>');
  document.write('  <nav class="site-nav" aria-label="主导航">');
  document.write('    <button class="menu-toggle" type="button" aria-expanded="false" aria-label="切换菜单">');
  document.write('      <span></span><span></span><span></span>');
  document.write('    </button>');
  document.write('    <ul class="nav-links">');
  document.write('      <li><a href="index.html">主页</a></li>');
  document.write('      <li><a href="donate.html">赞助</a></li>');
  document.write('      <li><a href="https://ifdian.net/a/jbs-comics?tab=shop">商城</a></li>');
  document.write('    </ul>');
  document.write('  </nav>');
  document.write('</header>');
  document.write('<script>');
  document.write('(function () {');
  document.write('  var toggle = document.querySelector(".menu-toggle");');
  document.write('  var links = document.querySelector(".nav-links");');
  document.write('  if (!toggle || !links) return;');
  document.write('  toggle.addEventListener("click", function () {');
  document.write('    var expanded = links.classList.toggle("is-open");');
  document.write('    toggle.setAttribute("aria-expanded", expanded ? "true" : "false");');
  document.write('  });');
  document.write('  document.addEventListener("click", function (event) {');
  document.write('    if (!event.target.closest(".site-nav")) {');
  document.write('      links.classList.remove("is-open");');
  document.write('      toggle.setAttribute("aria-expanded", "false");');
  document.write('    }');
  document.write('  });');
  document.write('})();');
  document.write('</script>');
})();
